config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  mount Api => '/api'

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'static_pages#index'

  resources :invites do
    member do
      post :accept, to: 'invites#accept', as: :accept
      post :cancel, to: 'invites#cancel', as: :cancel
      post :reject, to: 'invites#reject', as: :reject
    end
  end

  resources :users, only: :show
  resources :sits do
    resources :sitrequests do
      member do
        post :accept, to: 'sitrequests#accept', as: :accept
        post :cancel, to: 'sitrequests#cancel', as: :cancel
        post :reject, to: 'sitrequests#reject', as: :reject
      end
    end
  end
  

  resources :families
  resources :kids do
    resources :favorites
    resources :movies do
      collection { post :search, to: 'movies#index' }
    end
    resources :books do
      collection { post :search, to: 'books#index' }
    end
  end

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  include AASM

  enum invite_kind: {
    for_spouse: 0,
    for_sitter: 1,
  }

  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2,
    canceled: 3
  }

  aasm column: :status, enum: true do
    state :pending, initial: true
    state :accepted
    state :rejected
    state :canceled

    event :accept, after: :create_family_parent_or_sitter do
      transitions from: :pending, to: :accepted
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

    event :cancel do
      transitions from: :pending, to: :canceled
    end
  end

  belongs_to :family
  belongs_to :user

  validates :email, :invite_kind, presence: true

  before_create { self.code = SecureRandom.hex(32) }
  after_create { InviteMailer.send_invite(self).deliver_later }

  private

  def create_family_parent_or_sitter
    user = User.find_by_email email
    if user.parentuser? && for_spouse?
      user.family = family
    elsif for_sitter?
      if user.families.exists?(family)

      else
      user.families << family
      end
      user.update_attribute(:role, 3) if user.family.present?
    else
      raise ArgumentError, 'User kind and invite kind do not match'
    end
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_invite, only: [:show, :accept, :reject, :cancel]
  load_and_authorize_resource param_method: :invite_params

  def new
    @invite = current_user.invites.new
    @family = current_user.family

    case (@invite.invite_kind || params[:invite_kind])
    when 'for_spouse'
      @invite.invite_kind = 'for_spouse'
    when 'for_sitter'
      @invite.invite_kind = 'for_sitter'
    else
      redirect_to user_path(current_user)
    end
  end

  def create
    @invite = current_user.invites.new invite_params
    @invite.status = :pending
    @invite.family = current_user.family

    if @invite.save
      redirect_to user_path(current_user), notice: "Invite is sent to #{@invite.email}"
    else
      render :new
    end
  end

  def show
  end

  def accept
    @invite.accept!
    redirect_to user_path, notice: 'Accept invite successfully!'
  end

  def reject
    @invite.reject!
    redirect_to user_path, notice: 'Reject invite successfully!'
  end

  def cancel
    @invite.cancel!
    redirect_to root_path, notice: 'Cancel invite successfully!'
  end

  private

  def invite_params
    params.require(:invite).permit :email, :invite_kind
  end

  def set_invite
    @invite = Invite.find_by_code params[:id]
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/new.html.erb
<div class="booyah-box col-xs-4 col-xs-offset-4">
	<% if @invite.for_spouse? %>
	Invite Spouse

	<% elsif @invite.for_sitter? %>

	Invite Sitter

	<% end %>

	<%= simple_form_for @invite  do |f| %>
		<%= f.hidden_field :invite_kind %>
		<%= f.input :email, :hint => 'Email'  %>
		<%= f.submit 'Send Invite', :class=>"btn btn-primary" %>

	<% end %>
</div>
<br />
<% if @family.present? && @family.familysitters.present? %>
	<div class="col-xs-10 col-xs-offset-1">
		<h2 class="text-center">Current Family Sitters</h2>  <br /><br />
	  		<% @family.sitters.each do |sitter| %>
	  		<div class="col-xs-3 text-center">
	  			<div class="img-responsive family">
	  				<%= image_tag sitter.avatar.thumb, class: "img-circle avatar" if sitter.avatar.thumb.present? %>
	  			</div><br />
	  		 	<%= link_to sitter.first_name + " " + sitter.last_name, user_path(sitter) %><br />
	  			</div>
	  		<% end %>
	  	<br /><br />
		</div>
<% end %>

app/views/invites/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<% if @invite.pending? %>
		 
	You are invited to become a 
		<% if @invite.for_spouse? %>Parent<% else %>Sitter<% end %> of the <%= @invite.family.name %> family.<br /><br />

		   <%= link_to 'Accept', accept_invite_path, class: 'btn btn-success', method: :post %>
		 
		   <%= link_to 'Reject', reject_invite_path, class: 'btn btn-danger', method: :post %><br /><br />

		This invite is <%= @invite.status %>

	<% end %>

</div>