config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  mount Api => '/api'

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'static_pages#index'

  resources :invites do
    member do
      post :accept, to: 'invites#accept', as: :accept
      post :cancel, to: 'invites#cancel', as: :cancel
      post :reject, to: 'invites#reject', as: :reject
    end
  end

  resources :users, only: :show
  resources :sits do
    resources :sitrequests do
      member do
        post :accept, to: 'sitrequests#accept', as: :accept
        post :cancel, to: 'sitrequests#cancel', as: :cancel
        post :reject, to: 'sitrequests#reject', as: :reject
      end
    end
  end
  

  resources :families
  resources :kids do
    resources :favorites
    resources :movies do
      collection { post :search, to: 'movies#index' }
    end
    resources :books do
      collection { post :search, to: 'books#index' }
    end
  end

end

app/models/kid.rb
class Kid < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  include AvatarUrlable

  belongs_to :family
  has_many :favorites

  GENDER = {

    'Male' => 'M',
    'Female' => 'F'

  }.freeze

  validates :name, presence: true

  def as_json(options={})
    super(options.merge(methods: [:avatar_url], except: :avatar))
  end

end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update, :destroy]

  def index
  end

  def new
    @kid = Kid.new
  end

  def create
    @kid = current_user.family.kids.create(kid_params)
    if @kid.valid?
      redirect_to kid_path(@kid)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @kid = Kid.find(params[:id])
    @favorites = @kid.favorites.all
    @favorite = Favorite.new
  end

  def edit
    @kid = Kid.find(params[:id])
  end

  def update
    # We should find the record the user wants to update.
    # We should update this record and save the changes the user specifies into our database.
    # We should send the user back to the root page.

    @kid = Kid.find(params[:id])

    @kid.update_attributes(kid_params)

    if @kid.valid?
      redirect_to kid_path(@kid)
    else
      render :new, status: :unprocessable_entity
     end
  end

  def destroy
    @kid = Kid.find(params[:id])

    if @kid.family.parents.exists?(current_user)
      @kid.destroy
      redirect_to user_path
    else
      render :new, status: :unprocessable_entity
    end
    
  end

  private

  def kid_params
    params.require(:kid).permit(:user_id, :name, :birthdate, :gender, :avatar, :bedtime, :sleeproutine, :nap1, :nap2, :nap3, :naproutine, :allergies, :chores, :nonos)
  end
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/_booksearch.html.erb
<% if @booksearch.any? %>
<div class="booyah-box col-xs-6 col-xs-offset-2">
	<h3>Search Results</h3>

	<% @booksearch.each_with_index do |result, index| %>

		<%= simple_form_for @favorite, :url => kid_favorites_path(@kid) do |f| %>

				<%= f.hidden_field :name, value: result.title %>
	  		  	<%= f.hidden_field :book_isbn, value: result.isbn %>
	    		<%= f.hidden_field :description, value: result.description[0...350] if result.description %>
	    		<%= f.hidden_field :image_link, value: result.image_link %>
	  

	    		<%= image_tag result.image_link(:zoom => 6), class: "img-responsive " if result.image_link.present? %><br />
	    
			    Title: <%= result.title %><br />
			    Author: <%= result.authors %><br />
			    ISBN: <%= result.isbn %><br />
			    Description: <%= result.description[0...350]  if result.description %>...<br /><br />
	    
	    <%= f.submit '+Favorite Book', :class=> 'btn btn-primary' %><br /><br />
	  
		<% end %>

	
<% end %>
</div>
<% end %>

app/views/kids/edit.html.erb
  <div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2>Edit Kid</h2>
  <%= simple_form_for @kid do |f|  %>
  	 <div class= "row">
  	 	<div class="col-xs-2">
  	 		<div class="img-responsive">
				<%= image_tag @kid.avatar.thumb, class: "img-responsive circle-avatar img-circle kid" if @kid.avatar.present? %>
		 </div><br />
		</div>
	  	<div class="col-xs-4">
			<h2>General Info</h2>
			 	<%= f.input :name %>
				<%= f.input :birthdate, :label => 'Birth Date' %>
				<%= f.input :gender, :as =>:select, :collection => Kid::GENDER %><br />
				<strong>Profile Photo Upload</strong><br/>				
				<%= f.file_field :avatar %>
		</div>
		<div class="col-xs-6">
			<h3>No-Nos</h3>
			<%= f.input :allergies %>
			<%= f.input :nonos, :label => 'Please Avoid (Example: Screens before bed, Dairy)', :input_html => { :cols => 5, :rows => 7 }   %><br />
		</div>
		
    </div>
    <hr>
    <div class= "row">
    	<div class="col-xs-12">
    	  <h3>Eat Details</h3>
    	  <div class="col-xs-4">
				<%= f.input :breakfasttime, :label => 'Breakfast Time', :as => :time, :minute_step => 15 , default: Time.parse("7:00")%>
				<%= f.input :breakfastdetails, :label => 'Details',:input_html => { :cols => 5, :rows => 2 }   %>
			<br /><br />
		  </div>
		  <div class="col-xs-4">
				<%= f.input :lunchtime, :label => 'Lunch Time',:as => :time, :minute_step => 15 , default: Time.parse("12:00")%>
				<%= f.input :lunchdetails, :label => 'Details',:input_html => { :cols => 5, :rows => 2 }   %>
			<br /><br />
		  </div>
		  <div class="col-xs-4">
				<%= f.input :dinnertime, :label => 'Dinner Time', :as => :time, :minute_step => 15 , default: Time.parse("5:30")%>
				<%= f.input :dinnerdetails, :label => 'Details',:input_html => { :cols => 5, :rows => 2 }   %>
			<br /><br />
		  </div>
		  <div class="col-xs-4">
				<%= f.input :snack1time, :label => 'Snack Time 1', :as => :time, :minute_step => 15 , default: Time.parse("10:00")%>
				<%= f.input :snack1details, :label => 'Details',:input_html => { :cols => 5, :rows => 2 }   %>
			<br /><br />
		  </div>
		  <div class="col-xs-4">
				<%= f.input :snack2time, :label => 'Snack Time 2', :as => :time, :minute_step => 15 , default: Time.parse("3:00")%>
				<%= f.input :snack2details, :label => 'Details',:input_html => { :cols => 5, :rows => 2 }   %>
			<br /><br />
		  </div>
		  <div class="col-xs-4">
				<%= f.input :afterdinnertime, :label => 'Dream Feed (or dessert?)', :as => :time, :minute_step => 15 , default: Time.parse("8:00")%>
				<%= f.input :afterdinnerdetails, :label => 'Details',:input_html => { :cols => 5, :rows => 2 }   %>
			<br /><br />
		  </div>
		</div>
	</div>
	<hr>
	<div class= "row">
    	<div class="col-xs-12">	
		<div class="col-xs-6">
			<h3>Sleep</h3>
				<%= f.input :bedtime, :as => :time, :minute_step => 15 , default: Time.parse("7:30")%>
				<%= f.input :sleeproutine, :label => 'Sleep Routine',:input_html => { :cols => 5, :rows => 7 }   %>
			<br />
		</div>
		<div class="col-xs-6">
			<h3>Naps</h3>	
			<div class="form-inline text-center">
				<%= f.input :nap1, :as => :time, :minute_step => 15 , default: Time.parse("00:00") %>
				<%= f.input :nap2, :as => :time, :minute_step => 15 , default: Time.parse("00:00"),  :class=>"naptimes" %>
				<%= f.input :nap3, :as => :time, :minute_step => 15 , default: Time.parse("00:00"),  :class=>"naptimes" %>		
			</div><br />
				<%= f.input :naproutine, :label => 'Nap Time Routine',:input_html => { :cols => 5, :rows => 7 }   %>
		</div>
	</div>
		
	</div>
		<%= f.submit 'Update Kid', :class=>"btn btn-primary" %>
	<% end %>

</div> 

app/views/kids/index.html.erb
<% if @kids.present? %>
<% @kids.each do |kid| %>
	<div class="booyah-box col-xs-4 col-xs-offset-1">
        <div class="img-responsive">
        <%= image_tag kid.avatar, class: "img-circle avatar" if kid.avatar.present? %>
        </div>
		<h1><%= link_to kid.name, kid_path(kid) %></h1><br />
		<i><%= kid.birthdate %></i><br /><br />
		<p><%= kid.gender %></p>
	  </div>
<% end %>

<br />
<% end %>

app/views/kids/new.html.erb
  <div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add Kid</h1>
  <%= simple_form_for @kid do |f|  %>
  	 <div class= "row">
	  	<div class="col-xs-4">
			<h2>General Info</h2>
			 	<%= f.input :name %>
				<%= f.input :birthdate, :label => 'Birth Date' %>
				<%= f.input :gender, :as =>:select, :collection => Kid::GENDER %><br />
				<strong>Profile Photo Upload</strong><br/>				
				<%= f.file_field :avatar %>
		</div>
		
    </div>
    <hr>
    <div class= "row">
		<div class="col-xs-4">
			<h3>Sleep</h3><br />
				<%= f.input :bedtime, :as => :time, :minute_step => 15 , default: Time.parse("7:30")%>
				<%= f.input :sleeproutine, :label => 'Sleep Routine',:input_html => { :cols => 5, :rows => 7 }   %><br />
			<h3>Naptimes</h3><br />
			<small>All Optional</small>
				Nap 1:<%= f.input :nap1, :as => :time, :minute_step => 15 , default: Time.parse("9:30")%>Nap 2:<%= f.input :nap2, :as => :time, :minute_step => 15 , default: Time.parse("12:30")%><%= f.input :nap3, :as => :time, :minute_step => 15 , default: Time.parse("3:30")%>
				<%= f.input :naproutine, :label => 'Naptime Routine',:input_html => { :cols => 5, :rows => 7 }   %>
		</div>
		<div class="col-xs-4">
			<h3>No-Nos</h3><br />
			<%= f.input :allergies %>
			<%= f.input :nonos, :label => 'Please Avoid', :input_html => { :cols => 5, :rows => 7 }   %><br />
		</div>
		
	</div>
		<%= f.submit 'Add Kid', :class=>"btn btn-primary" %>
	<% end %>

</div> 

app/views/kids/show.html.erb
<div class="row">
	  <div class="col-md-10 col-xs-10 col-xs-offset-1">
		<div class="col-xs-4 text-center">
			<h4>Kid</h4>
			<div class="img-responsive">
					<%= image_tag @kid.avatar.thumb, class: "img-responsive img-circle circle-avatar kid" if @kid.avatar.present? %>
			 </div><br />
			 <div class="caption">
				 <h4><%= @kid.name %></h4>
				 <% bday = @kid.birthdate %>
				 <i><%= bday.strftime("%B") + " " + bday.strftime("%d") + ", " + bday.strftime("%Y") %></i><br /><br />
			 </div>
	    	    <% if @kid.family.parents.exists?(current_user)  %>
				<%= link_to 'Edit', edit_kid_path(@kid), :class => 'btn btn-default btn-sm' %>
				 <%= link_to 'Delete Kid', kid_path(@kid), :method => :delete, :data => {:confirm => 'Please confirm deletion.  Data cannot be restored.'}, :class => 'btn btn-primary btn-cons btn-sm' %>
		        <% end %>
	    </div>	
	   	<div class="col-xs-8">
	   		<br /><br /><br /><br />
	   		<div class="col-xs-6">
				<div class="panel pull-down panel-default">
					  <div class="panel-head-custom panel-heading">
					    <h3 class="panel-title">Medical</h3>
					  </div>
					  <div class="panel-body">
					   <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#kidMedicalInfo">
			        			MEDICAL INFO
			    		  </button>  
					  </div>
				</div>
				<div class="panel pull-down panel-default">
					  <div class="panel-head-custom panel-heading">
					    <h3 class="panel-title">Emergency Contacts</h3>
					  </div>
					  <div class="panel-body">
					   <%= @kid.family.emerg_contact_1 %><br />
					   <%= @kid.family.emerg_contact_1_phone %>
						<br /><br />
					  <% if @kid.family.emerg_contact_2 %>
					   <%= @kid.family.emerg_contact_2 %><br />
					   <%= @kid.family.emerg_contact_2_phone %>
					  <% end %>
					  </div>
				</div><br /><br />
			</div>
			<div class="col-xs-6">
				<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title">No-Nos</h3>
				  </div>
				  <div class="panel-body">
				   Allergies: <br/><%= @kid.allergies %><br /><br />
				   Please avoid:<br/><%= @kid.nonos %><br />

				  </div>
				</div>
			</div>
		</div>
				
	</div>

	<br /><br />
	<div class="clear"></div>

	<div class="row">
		<div class="col-md-10 col-xs-10 col-xs-offset-1">
			<div class="col-xs-8">
				<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title" >Eat Routine</h3> 
				  </div>
				  <div class="panel-body">
				  
				  </div>
				</div>
			</div>
			<div class="col-xs-4">
				<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title" >SLEEP</h3>
				  </div>
				  <div class="panel-body">
				   			<i>Bed Time: </i><strong><%= @kid.bedtime.strftime("%l")%>:<%= @kid.bedtime.strftime("%M")%></strong><br />
				   			<br/><%= @kid.sleeproutine %><br />
						<br />
				  	<div class="row">
				  		<div class="col-xs-4"><i>Nap 1:</i><strong><%= @kid.nap1.strftime("%l")%>:<%= @kid.nap1.strftime("%M")%></strong></div>
				  		<div class="col-xs-4"><i>Nap 2:</i><strong><%= @kid.nap2.strftime("%l")%>:<%= @kid.nap2.strftime("%M")%></strong></div>
				  		<div class="col-xs-4"><i>Nap 3:</i><strong><%= @kid.nap3.strftime("%l")%>:<%= @kid.nap3.strftime("%M")%></strong></div>
				  	</div><br/>
				     	  <br/><%= @kid.naproutine %><br />

					<br />
				  </div>
				</div>
			</div>
		</div>
	</div>

	<div class="clear"></div>

	<div class="col-md-10 col-xs-10 col-xs-offset-1"><h3><%= @kid.name %>'s Favorites <%= link_to ' (Edit)', kid_favorites_path(@kid) if @kid.family.parents.exists?(current_user) %></h3>
	</div>

	<!-- Favorites Section: Books and Movies -->
	<div class="row">
		<div class="col-md-10 col-xs-10 col-xs-offset-1">
			<div class="col-xs-12">
				<div class="panel panel-default">
					  <div class="panel-heading">
					    <h3 class="panel-title">Favorite Activities</h3>
					  </div>
					  <div class="panel-body">
					  <% if @favorites.any? %>
					   		<% @favorites.each do |activity, index| %>
						   		<% if activity.category == 'activity' %>
								<div class="col-xs-4 col-sm-4 hideOverflow">
									<b><%= activity.name %></b><br />
					    			<b>Description:</b> <%= activity.description %><br />
								</div>
								<% end %>
							<% end %>
					    <br />
					  <% end %>
		   			</div>
		   			<br /><br />
		   			<% if @kid.family.parents.exists?(current_user) %>
		   			 <div class="panel-footer">
						  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myFavoriteModal">
			        			Add Favorite
			    		  </button>  
			    	 </div>
				    <% end %>
			</div>
			</div>

			<div class="col-xs-12">
				<div class="panel panel-default">
					  <div class="panel-heading">
					    <h3 class="panel-title">Favorite Books</h3>
					  </div>
					  <div class="panel-body">
					  <% if @favorites.any? %>
					   <%	@favorites.each do |book, index| %>
					   		<% if book.category == 'book' %>
							<div class="col-xs-4 col-sm-4 hideOverflow">
								<%= image_tag book.image_link, class: "img-responsive " if book.image_link.present? %><br /><br />
								<b>Title:</b> <%= book.name %><br />
				    			<b>Description:</b> <%= book.description %><br />
							</div>
							<% end %>
						<% end %>
					    <br />
					 <% end %>
					 <br /><br />
					 </div>
					<% if @kid.family.parents.exists?(current_user) %>
					  <div class="panel-footer">
					 	<%= link_to 'Add Favorite Book', new_kid_book_path(@kid), :class => 'btn btn-primary' %>
					 </div>
					<% end %>
					
				</div>
			</div>

			<div class="col-xs-12">
				<div class="panel panel-default">
					  <div class="panel-heading">
					    <h3 class="panel-title">Favorite Movies</h3>
					  </div>
					  <div class="panel-body">
					  <% if @favorites.any? %>
					   <%	@favorites.each do |movie, index| %>
					   		<% if movie.category == 'movie' %>
							<div class="col-xs-4 col-sm-4 hideOverflow">
								<%= image_tag movie.image_link, class: "img-responsive " if movie.image_link.present? %><br /><br />
								<b>Title:</b> <%= movie.name %><br />
				    			<b>Released:</b> <%= movie.releasedate %><br />
				    			<b>Overview:</b> <%= movie.description %><br />
							</div>
							<% end %>
						<% end %>
					    <br />
					 <% end %>
					 <br /><br />
					 </div>
					 <% if @kid.family.parents.exists?(current_user) %>
					 <div class="panel-footer">
					 	<%= link_to 'Add Favorite Movie', new_kid_movie_path(@kid), :class => 'btn btn-primary' %>
					 </div>
					 <% end %>
					
					</div>
				</div>
			</div>
		</div>
</div>



<!-- Modal -->
			<div class="modal fade" id="kidMedicalInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel">Medical</h4>
			      </div>
			      <div class="modal-body">
			    	 Insurance Provider: <%= @kid.family.insuranceprovider %><br />
					   Enrollee ID: <%= @kid.family.health_ins_enrollee_id %><br />
					   Group #: <%= @kid.family.health_ins_group_num %><br />
					   Physician Name: <%= @kid.family.physicianname %><br />
					   Physician Phone: <%= @kid.family.physicianphone %><br />
					   <br />  	
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			      </div>
			    </div>
			</div>

			<div class="modal fade" id="myFavoriteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel">Add Favorite Activity</h4>
			      </div>
			      <div class="modal-body">
			      
				<%= simple_form_for @favorite, :url => kid_favorites_path(@kid) do |f| %>
				<%= f.hidden_field :category, value: "activity" %>
				<%= f.input :name %>
				<%= f.input :description, :label => 'Details' %>
				<br />

				
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			        <%= f.submit 'Add Favorite', :class=> 'btn btn-primary' %>
			        <% end %>
			      </div>
			    </div>
			</div>