config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  mount Api => '/api'

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'static_pages#index'

  resources :invites do
    member do
      post :accept, to: 'invites#accept', as: :accept
      post :cancel, to: 'invites#cancel', as: :cancel
      post :reject, to: 'invites#reject', as: :reject
    end
  end

  resources :users, only: :show
  resources :sits do
    resources :sitrequests do
      member do
        post :accept, to: 'sitrequests#accept', as: :accept
        post :cancel, to: 'sitrequests#cancel', as: :cancel
        post :reject, to: 'sitrequests#reject', as: :reject
      end
    end
  end
  

  resources :families
  resources :kids do
    resources :favorites
    resources :movies do
      collection { post :search, to: 'movies#index' }
    end
    resources :books do
      collection { post :search, to: 'books#index' }
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, User
    can :read, Family
    can [:create], Family
    can [:edit], Family if user.parentuser? || user.parentsitteruser?
    can [:update], Family do |family|
      user.family == family
    end
    
    can :read, Invite do |invite|
      invite.email == user.email
    end
    can [:accept, :reject], Invite do |invite|
      invite.email == user.email
    end
    can :cancel, Invite do |invite|
      invite.family == user.family
    end
    can :create, Invite if user.parentuser? || user.parentsitteruser?
    can :create, Sitrequest
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :favorite
end

app/models/family.rb
class Family < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  include AvatarUrlable

  has_many :parenthoods
  has_many :users, through: :parenthoods
  has_many :kids
  has_many :familysitters
  has_many :sitters, through: :familysitters
  has_many :invites
  has_many :sits

  validates :name, presence: true

  accepts_nested_attributes_for :kids, reject_if: :all_blank, allow_destroy: true
  # for ActiveAdmin
  accepts_nested_attributes_for :users, :sitters

  alias parents users

  def may_invite_spouse?
    parents.count < 2
  end

  def as_json(options={})
    super(options.merge(methods: [:avatar_url], exclude: :avatar))
  end
end

app/models/familysitter.rb
class Familysitter < ActiveRecord::Base
  belongs_to :sitter, class_name: User
  belongs_to :family
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :kid

  CATEGORIES = {

    'Activity' => 'activity',
    'Book' => 'book',
    'Movie' => 'movie'

  }.freeze
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  include AASM

  enum invite_kind: {
    for_spouse: 0,
    for_sitter: 1,
  }

  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2,
    canceled: 3
  }

  aasm column: :status, enum: true do
    state :pending, initial: true
    state :accepted
    state :rejected
    state :canceled

    event :accept, after: :create_family_parent_or_sitter do
      transitions from: :pending, to: :accepted
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

    event :cancel do
      transitions from: :pending, to: :canceled
    end
  end

  belongs_to :family
  belongs_to :user

  validates :email, :invite_kind, presence: true

  before_create { self.code = SecureRandom.hex(32) }
  after_create { InviteMailer.send_invite(self).deliver_later }

  private

  def create_family_parent_or_sitter
    user = User.find_by_email email
    if user.parentuser? && for_spouse?
      user.family = family
    elsif for_sitter?
      if user.families.exists?(family)

      else
      user.families << family
      end
      user.update_attribute(:role, 3) if user.family.present?
    else
      raise ArgumentError, 'User kind and invite kind do not match'
    end
  end
end

app/models/kid.rb
class Kid < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  include AvatarUrlable

  belongs_to :family
  has_many :favorites

  GENDER = {

    'Male' => 'M',
    'Female' => 'F'

  }.freeze

  validates :name, presence: true

  def as_json(options={})
    super(options.merge(methods: [:avatar_url], except: :avatar))
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  Tmdb::Api.key("omdb_api_key")
  belongs_to :favorite
end

app/models/parent.rb
class Parent < User
  has_one :parenthood
  has_one :family, through: parenthood
end

app/models/parenthood.rb
class Parenthood < ActiveRecord::Base
  belongs_to :family
  belongs_to :user
end

app/models/sit.rb
class Sit < ActiveRecord::Base
	belongs_to :family
	has_many :sitrequests
end

app/models/sitrequest.rb
class Sitrequest < ActiveRecord::Base
  include AASM

  enum invite_kind: {
    for_sitter: 1,
  }

  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2,
    canceled: 3
  }

  aasm column: :status, enum: true do
    state :pending, initial: true
    state :accepted
    state :rejected
    state :canceled

    event :accept, after: :add_sitter_to_sit do
      transitions from: :pending, to: :accepted
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

    event :cancel do
      transitions from: :pending, to: :canceled
    end
  end

  belongs_to :sit

  validates :email, :invite_kind, presence: true 

  before_create { self.code = SecureRandom.hex(32) }
  after_create { SitRequestMailer.send_sitrequest(self).deliver_later }

  private

  def add_sitter_to_sit
    user = User.find_by_email email
    
      if sit.sitter_id.present?
      	raise ArgumentError, 'Sit Already Booked'
      else
      	 sit.sitter_id = user
      end
      
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  include AvatarUrlable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true

  # for parents
  has_one :parenthood
  has_one :family, through: :parenthood

  # invites
  has_many :invites

  # for Sitter only
  has_many :familysitters, foreign_key: :sitter_id
  has_many :families, through: :familysitters, source: :family
  has_many :kids, through: :family

  # Access Token
  has_many :access_token, class_name: 'Doorkeeper::AccessToken', foreign_key: :resource_owner_id

  enum role: {
    # Person with Kids, Family, But Does not Sit for Others
    parentuser: 1,
    # Person who watches for families, but doesn't have family.
    sitteruser: 2,
    # Person with Kids, Family, also been invited to view/sit for other families.
    parentsitteruser: 3
  }

  validates :role, presence: true

  def access_token(application=nil)
    application = Doorkeeper::Application.where(name: 'default', redirect_uri: 'urn:ietf:wg:oauth:2.0:oob').first_or_create unless application
    Doorkeeper::AccessToken.create(application: application, resource_owner_id: id).token
  end

  def as_json(options=nil)
    options = options || {}
    super(options.merge(methods: [:access_token, :name, :avatar_url], except: :avatar))
  end


  def name
    super || first_name.to_s + ' ' + last_name.to_s
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update, :destroy]

  def index
    @kid = Kid.find(params[:kid_id])
    @favorites = @kid.favorites.all
  end

  def new
    @kid = Kid.find(params[:kid_id])
    @favorites = @kid.favorites.all
    @favorite = Favorite.new
  end

  def show
    @kid = Kid.find(params[:kid_id])
    @favorites = @kid.favorites.all
  end

  def create
    @kid = Kid.find(params[:kid_id])
    # Prevent Duplicate Foods
    @kid.favorites.create(favorite_params.merge(kid_id: @kid.id))
    redirect_to kid_path(@kid)
  end

  def destroy
    @kid = Kid.find(params[:kid_id])
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to kid_path(@kid)
  end

  private

  def favorite_params
    params.require(:favorite).permit(:type, :name, :description, :image_link, :book_isbn, :movie_cast, :releasedate, :movie_trailer_url, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sits_helper.rb
module SitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/edit.html.erb
<!-- Favorites Section: Food, Drinks, Activities -->
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
	<h2><%= @kid.name %>'s Favorites: Remove</h2><br/>
		<div class="col-xs-4">
				  <h3>Favorite Foods</h3>
				  <hr>
				  <% if @favorites.any? %>
				   <%	@favorites.each do |food| %>
				   		<% if food.category == 'food' %>
							<h4><%= food.name %></h4>
							<% if !food.description.empty? %>
			    				<b>Details:</b> <%= food.description %><br/>
			    			<% end %><br /><br />
			    			<%= link_to 'Remove', kid_favorite_path(@kid, food.id), :method => :delete %> <i class="fa fa-trash"></i>
						<% end %>
					<% end %>
				    <br />
				 <% end %>
		</div>

		<div class="col-xs-4">
				  <h3>Favorite Drinks</h3>
				  <hr>
				  <% if @favorites.any? %>
				   <%	@favorites.each do |drink| %>
				   		<% if drink.category == 'drink' %>
							<h4><%= drink.name %></h4>
							<% if !drink.description.empty? %>
			    				<b>Details:</b> <%= drink.description %>
			    			<% end %><br /><br />
						<% end %>
					<% end %>
				    <br />
				 <% end %>
		</div>

		<div class="col-xs-4">
		
				  <h3>Favorite Activities</h3>
				  <hr>
				  <% if @favorites.any? %>
				   <%	@favorites.each do |activity| %>
				   		<% if activity.category == 'activity' %>
							<h4><%= activity.name %></h4>
							<% if !activity.description.empty? %>
			    				<b>Details:</b> <%= activity.description %>
			    			<% end %><br /><br />
						<% end %>
					<% end %>
				    <br />
				 <% end %>
		</div>
		<div class="clear"></div>
		<% if @kid.family.parents.exists?(current_user) %>
		<button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#myFavoriteModal">
	        Add Favorite
	     </button>
	    <% end %>

	</div>
</div>
<br /><br /><br />


<!-- Favorites Section: Books and Movies -->
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<div class="col-xs-12">
			<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title">Favorite Books</h3>
				  </div>
				  <div class="panel-body">
				  <% if @favorites.any? %>
				   <%	@favorites.each do |book, index| %>
				   		<% if book.category == 'book' %>
						<div class="col-xs-4 col-sm-4 hideOverflow">
							<%= image_tag book.image_link, class: "img-responsive " if book.image_link.present? %><br /><br />
							<b>Title:</b> <%= book.name %><br />
			    			<b>Description:</b> <%= book.description %><br />
						</div>
						<% end %>
					<% end %>
				    <br />
				 <% end %>
				 <br /><br />
				 </div>
				<% if @kid.family.parents.exists?(current_user) %>
				  <div class="panel-footer">
				 	<%= link_to 'Add Favorite Book', new_kid_book_path(@kid), :class => 'btn btn-primary' %>
				 </div>
				<% end %>
				
			</div>
		</div>

		<div class="col-xs-12">
			<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title">Favorite Movies</h3>
				  </div>
				  <div class="panel-body">
				  <% if @favorites.any? %>
				   <%	@favorites.each do |movie, index| %>
				   		<% if movie.category == 'movie' %>
						<div class="col-xs-4 col-sm-4 hideOverflow">
							<%= image_tag movie.image_link, class: "img-responsive " if movie.image_link.present? %><br /><br />
							<b>Title:</b> <%= movie.name %><br />
			    			<b>Cast:</b> <%= movie.movie_cast %><br />
			    			<b>Trailer:</b> <%= movie.movie_trailer_url %><br />
						</div>
						<% end %>
					<% end %>
				    <br />
				 <% end %>
				 <br /><br />
				 </div>
				 <% if @kid.family.parents.exists?(current_user) %>
				 <div class="panel-footer">
				 	<%= link_to 'Add Favorite Movie', new_kid_movie_path(@kid), :class => 'btn btn-primary' %>
				 </div>
				 <% end %>
				
			</div>
		</div>
	</div>
</div>

app/views/favorites/index.html.erb
<!-- Favorites Section: Food, Drinks, Activities -->
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
	<h2><%= @kid.name %>'s Favorites: Remove</h2><br/>
		<div class="col-xs-12">
		
				  <h3>Favorite Activities</h3>
				  <hr>
				  <% if @favorites.any? %>
				   <%	@favorites.each do |activity| %>
				   	<div class="col-xs-4">
				   		<% if activity.category == 'activity' %>
							<h4><%= activity.name %></h4>
							<% if !activity.description.empty? %>
			    				<b>Details:</b> <%= activity.description %>
			    			<% end %><br /><br />
			    			<%= link_to 'Remove', kid_favorite_path(@kid, activity.id), :method => :delete %> <i class="fa fa-trash"></i>
						<% end %>
					</div>
					<% end %>
				    <br />
				 <% end %>
		</div>
		<div class="clear"></div>
		<% if @kid.family.parents.exists?(current_user) %>
		<button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#myFavoriteModal">
	        Add Favorite
	     </button>
	    <% end %>

	</div>
</div>
<br /><br /><br />


<!-- Favorites Section: Books and Movies -->
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<div class="col-xs-12">
			<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title">Favorite Books</h3>
				  </div>
				  <div class="panel-body">
				  <% if @favorites.any? %>
				   <%	@favorites.each do |book, index| %>
				   		<% if book.category == 'book' %>
						<div class="col-xs-4 col-sm-4 hideOverflow">
							<%= image_tag book.image_link, class: "img-responsive " if book.image_link.present? %><br /><br />
							<b>Title:</b> <%= book.name %><br />
			    			<b>Description:</b> <%= book.description %><br />
			    			<%= link_to 'Remove', kid_favorite_path(@kid, book.id), :method => :delete %> <i class="fa fa-trash"></i>
						</div>
						<% end %>
					<% end %>
				    <br />
				 <% end %>
				 <br /><br />
				 </div>
				<% if @kid.family.parents.exists?(current_user) %>
				  <div class="panel-footer">
				 	<%= link_to 'Add Favorite Book', new_kid_book_path(@kid), :class => 'btn btn-primary' %>
				 </div>
				<% end %>
				
			</div>
		</div>


		<div class="col-xs-12">
			<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title">Favorite Movies</h3>
				  </div>
				  <div class="panel-body">
				  <% if @favorites.any? %>
				   <%	@favorites.each do |movie, index| %>
				   		<% if movie.category == 'movie' %>
						<div class="col-xs-4 col-sm-4 hideOverflow">
							<%= image_tag movie.image_link, class: "img-responsive " if movie.image_link.present? %><br /><br />
							<b>Title:</b> <%= movie.name %><br />
			    			<%= link_to 'Remove', kid_favorite_path(@kid, movie.id), :method => :delete %> <i class="fa fa-trash"></i>
						</div>
						<% end %>
					<% end %>
				    <br />
				 <% end %>
				 <br /><br />
				 </div>
				<% if @kid.family.parents.exists?(current_user) %>
				  <div class="panel-footer">
				 	<%= link_to 'Add Favorite Movie', new_kid_movie_path(@kid), :class => 'btn btn-primary' %>
				 </div>
				<% end %>
				
			</div>
		</div>
		
	</div>
</div>

app/views/favorites/new.html.erb
<div class="booyah-box col-xs-4 col-xs-offset-2">
	  <h3>Add A Book</h3>
			<%= form_tag new_kid_favorite_path, :method => :get do |f| %>
			<%= text_field_tag :name, params[:name] %>
			<%= submit_tag "Search", :name => nil, :class=>"btn btn-primary"  %>
		<% end %>
</div>
<% if @booksearch.nil?  %>
    <% puts "Search Empty" %>
<% else %>
<div class="booyah-box col-xs-6 col-xs-offset-2">
	<h3>Search Results</h3>

	<% @booksearch.each_with_index do |result, index| %>

		<%= simple_form_for @favorite, :url => kid_favorites_path(@kid) do |f| %>
				<%  @formtype = 'book' %>
				<%= f.hidden_field :name, value: result.title %>
	  		  	<%= f.hidden_field :book_isbn, value: result.isbn %>
	    		<%= f.hidden_field :description, value: result.description[0...350] if result.description %>
	    		<%= f.hidden_field :image_link, value: result.image_link %>
	  			<%= f.hidden_field :category, value: @formtype %>

	    		<%= image_tag result.image_link(:zoom => 6), class: "img-responsive " if result.image_link.present? %><br />
	    
			    Title: <%= result.title %><br />
			    Author: <%= result.authors %><br />
			    ISBN: <%= result.isbn %><br />
			    Description: <%= result.description[0...350]  if result.description %>...<br /><br />
	    
	    <%= f.submit '+Favorite Book', :class=> 'btn btn-primary' %><br /><br />
	  
		<% end %>
<% end %>
</div>
<% end %>

app/views/favorites/show.html.erb
<!-- Favorites Section: Food, Drinks, Activities -->
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
	<h2><%= @kid.name %>'s Favorites: Remove</h2><br/>
		<div class="col-xs-4">
				  <h3>Favorite Foods</h3>
				  <hr>
				  <% if @favorites.any? %>
				   <%	@favorites.each do |food| %>
				   		<% if food.category == 'food' %>
							<h4><%= food.name %></h4>
							<% if !food.description.empty? %>
			    				<b>Details:</b> <%= food.description %><br/>
			    			<% end %><br /><br />
			    			<%= link_to 'Remove', kid_favorite_path(@kid, food.id), :method => :delete %> <i class="fa fa-trash"></i>
						<% end %>
					<% end %>
				    <br />
				 <% end %>
		</div>

		<div class="col-xs-4">
				  <h3>Favorite Drinks</h3>
				  <hr>
				  <% if @favorites.any? %>
				   <%	@favorites.each do |drink| %>
				   		<% if drink.category == 'drink' %>
							<h4><%= drink.name %></h4>
							<% if !drink.description.empty? %>
			    				<b>Details:</b> <%= drink.description %>
			    			<% end %><br /><br />
						<% end %>
					<% end %>
				    <br />
				 <% end %>
		</div>

		<div class="col-xs-4">
		
				  <h3>Favorite Activities</h3>
				  <hr>
				  <% if @favorites.any? %>
				   <%	@favorites.each do |activity| %>
				   		<% if activity.category == 'activity' %>
							<h4><%= activity.name %></h4>
							<% if !activity.description.empty? %>
			    				<b>Details:</b> <%= activity.description %>
			    			<% end %><br /><br />
						<% end %>
					<% end %>
				    <br />
				 <% end %>
		</div>
		<div class="clear"></div>
		<% if @kid.family.parents.exists?(current_user) %>
		<button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#myFavoriteModal">
	        Add Favorite
	     </button>
	    <% end %>

	</div>
</div>
<br /><br /><br />


<!-- Favorites Section: Books and Movies -->
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<div class="col-xs-12">
			<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title">Favorite Books</h3>
				  </div>
				  <div class="panel-body">
				  <% if @favorites.any? %>
				   <%	@favorites.each do |book, index| %>
				   		<% if book.category == 'book' %>
						<div class="col-xs-4 col-sm-4 hideOverflow">
							<%= image_tag book.image_link, class: "img-responsive " if book.image_link.present? %><br /><br />
							<b>Title:</b> <%= book.name %><br />
			    			<b>Description:</b> <%= book.description %><br />
						</div>
						<% end %>
					<% end %>
				    <br />
				 <% end %>
				 <br /><br />
				 </div>
				<% if @kid.family.parents.exists?(current_user) %>
				  <div class="panel-footer">
				 	<%= link_to 'Add Favorite Book', new_kid_book_path(@kid), :class => 'btn btn-primary' %>
				 </div>
				<% end %>
				
			</div>
		</div>

		<div class="col-xs-12">
			<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title">Favorite Movies</h3>
				  </div>
				  <div class="panel-body">
				  <% if @favorites.any? %>
				   <%	@favorites.each do |movie, index| %>
				   		<% if movie.category == 'movie' %>
						<div class="col-xs-4 col-sm-4 hideOverflow">
							<%= image_tag movie.image_link, class: "img-responsive " if movie.image_link.present? %><br /><br />
							<b>Title:</b> <%= movie.name %><br />
			    			<b>Cast:</b> <%= movie.movie_cast %><br />
			    			<b>Trailer:</b> <%= movie.movie_trailer_url %><br />
						</div>
						<% end %>
					<% end %>
				    <br />
				 <% end %>
				 <br /><br />
				 </div>
				 <% if @kid.family.parents.exists?(current_user) %>
				 <div class="panel-footer">
				 	<%= link_to 'Add Favorite Movie', new_kid_movie_path(@kid), :class => 'btn btn-primary' %>
				 </div>
				 <% end %>
				
			</div>
		</div>
	</div>
</div>