config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  mount Api => '/api'

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'static_pages#index'

  resources :invites do
    member do
      post :accept, to: 'invites#accept', as: :accept
      post :cancel, to: 'invites#cancel', as: :cancel
      post :reject, to: 'invites#reject', as: :reject
    end
  end

  resources :users, only: :show
  resources :sits do
    resources :sitrequests do
      member do
        post :accept, to: 'sitrequests#accept', as: :accept
        post :cancel, to: 'sitrequests#cancel', as: :cancel
        post :reject, to: 'sitrequests#reject', as: :reject
      end
    end
  end
  

  resources :families
  resources :kids do
    resources :favorites
    resources :movies do
      collection { post :search, to: 'movies#index' }
    end
    resources :books do
      collection { post :search, to: 'books#index' }
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, User
    can :read, Family
    can [:create], Family
    can [:edit], Family if user.parentuser? || user.parentsitteruser?
    can [:update], Family do |family|
      user.family == family
    end
    
    can :read, Invite do |invite|
      invite.email == user.email
    end
    can [:accept, :reject], Invite do |invite|
      invite.email == user.email
    end
    can :cancel, Invite do |invite|
      invite.family == user.family
    end
    can :create, Invite if user.parentuser? || user.parentsitteruser?
    can :create, Sitrequest
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :favorite
end

app/models/family.rb
class Family < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  include AvatarUrlable

  has_many :parenthoods
  has_many :users, through: :parenthoods
  has_many :kids
  has_many :familysitters
  has_many :sitters, through: :familysitters
  has_many :invites
  has_many :sits

  validates :name, presence: true

  accepts_nested_attributes_for :kids, reject_if: :all_blank, allow_destroy: true
  # for ActiveAdmin
  accepts_nested_attributes_for :users, :sitters

  alias parents users

  def may_invite_spouse?
    parents.count < 2
  end

  def as_json(options={})
    super(options.merge(methods: [:avatar_url], exclude: :avatar))
  end
end

app/models/familysitter.rb
class Familysitter < ActiveRecord::Base
  belongs_to :sitter, class_name: User
  belongs_to :family
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :kid

  CATEGORIES = {

    'Activity' => 'activity',
    'Book' => 'book',
    'Movie' => 'movie'

  }.freeze
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  include AASM

  enum invite_kind: {
    for_spouse: 0,
    for_sitter: 1,
  }

  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2,
    canceled: 3
  }

  aasm column: :status, enum: true do
    state :pending, initial: true
    state :accepted
    state :rejected
    state :canceled

    event :accept, after: :create_family_parent_or_sitter do
      transitions from: :pending, to: :accepted
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

    event :cancel do
      transitions from: :pending, to: :canceled
    end
  end

  belongs_to :family
  belongs_to :user

  validates :email, :invite_kind, presence: true

  before_create { self.code = SecureRandom.hex(32) }
  after_create { InviteMailer.send_invite(self).deliver_later }

  private

  def create_family_parent_or_sitter
    user = User.find_by_email email
    if user.parentuser? && for_spouse?
      user.family = family
    elsif for_sitter?
      if user.families.exists?(family)

      else
      user.families << family
      end
      user.update_attribute(:role, 3) if user.family.present?
    else
      raise ArgumentError, 'User kind and invite kind do not match'
    end
  end
end

app/models/kid.rb
class Kid < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  include AvatarUrlable

  belongs_to :family
  has_many :favorites

  GENDER = {

    'Male' => 'M',
    'Female' => 'F'

  }.freeze

  validates :name, presence: true

  def as_json(options={})
    super(options.merge(methods: [:avatar_url], except: :avatar))
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  Tmdb::Api.key("omdb_api_key")
  belongs_to :favorite
end

app/models/parent.rb
class Parent < User
  has_one :parenthood
  has_one :family, through: parenthood
end

app/models/parenthood.rb
class Parenthood < ActiveRecord::Base
  belongs_to :family
  belongs_to :user
end

app/models/sit.rb
class Sit < ActiveRecord::Base
	belongs_to :family
	has_many :sitrequests
end

app/models/sitrequest.rb
class Sitrequest < ActiveRecord::Base
  include AASM

  enum invite_kind: {
    for_sitter: 1,
  }

  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2,
    canceled: 3
  }

  aasm column: :status, enum: true do
    state :pending, initial: true
    state :accepted
    state :rejected
    state :canceled

    event :accept, after: :add_sitter_to_sit do
      transitions from: :pending, to: :accepted
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

    event :cancel do
      transitions from: :pending, to: :canceled
    end
  end

  belongs_to :sit

  validates :email, :invite_kind, presence: true 

  before_create { self.code = SecureRandom.hex(32) }
  after_create { SitRequestMailer.send_sitrequest(self).deliver_later }

  private

  def add_sitter_to_sit
    user = User.find_by_email email
    
      if sit.sitter_id.present?
      	raise ArgumentError, 'Sit Already Booked'
      else
      	 sit.sitter_id = user
      end
      
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  include AvatarUrlable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true

  # for parents
  has_one :parenthood
  has_one :family, through: :parenthood

  # invites
  has_many :invites

  # for Sitter only
  has_many :familysitters, foreign_key: :sitter_id
  has_many :families, through: :familysitters, source: :family
  has_many :kids, through: :family

  # Access Token
  has_many :access_token, class_name: 'Doorkeeper::AccessToken', foreign_key: :resource_owner_id

  enum role: {
    # Person with Kids, Family, But Does not Sit for Others
    parentuser: 1,
    # Person who watches for families, but doesn't have family.
    sitteruser: 2,
    # Person with Kids, Family, also been invited to view/sit for other families.
    parentsitteruser: 3
  }

  validates :role, presence: true

  def access_token(application=nil)
    application = Doorkeeper::Application.where(name: 'default', redirect_uri: 'urn:ietf:wg:oauth:2.0:oob').first_or_create unless application
    Doorkeeper::AccessToken.create(application: application, resource_owner_id: id).token
  end

  def as_json(options=nil)
    options = options || {}
    super(options.merge(methods: [:access_token, :name, :avatar_url], except: :avatar))
  end


  def name
    super || first_name.to_s + ' ' + last_name.to_s
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @family = @user.family || Family.new
    @families = @user.families
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sits_helper.rb
module SitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="booyah-box special col-xs-10 col-xs-offset-1">
	<div class="content">
		<%= image_tag @family.avatar.family, class: "img-responsive booyah-box special" if @family.present? %>
		<br /><br /><br /><br /><br /><br /><br />
		<div class="col-xs-2">
		 	<div class="img-responsive img-thumbnail profile">
				<%= image_tag @user.avatar, class: "img-responsive avatar" if @user.avatar.present? %>
		    </div>	

		 </div>
		<div class="row">
		<div class="col-xs-10">
			<h3>     <%= @user.first_name %> <%= @user.last_name %> <%= @user.role %></h3>
		</div>
		<div class="col-xs-9">
		   <% if @family.present? && @user == current_user %>
				<% if @family.may_invite_spouse? %>
				   <%= link_to 'Invite Spouse/Partner',  new_invite_path(invite_kind: :for_spouse), :class => 'btn btn-primary btn-cons' %>
	    		<% end %>
	    		<%= link_to 'Invite Sitter',  new_invite_path(invite_kind: :for_sitter), :class => 'btn btn-primary btn-sm btn-cons' %>
	    		<%= link_to 'Edit Family Details/Photo',  edit_family_path(@family), :class => 'btn btn btn-primary btn-sm btn-cons' %>
	    		<%= link_to 'Create Sit',  new_sit_path, :class => 'btn btn btn-primary btn-sm btn-cons' %>
		   <% end %>
		 </div>
		</div>
	</div>
</div>
<% if @user.parentuser? || @user.parentsitteruser? && @user.family == @family && @user.family.present? %>
<!-- Section Kids --> 
<div class="kids_section">
	<div class="col-xs-10 col-xs-offset-1">
		<div class="col-xs-6" >
			<h2 class="text-center">Kids</h2> <br /><br />
		  		<% @family.kids.each do |kid| %>
		  		<div class="col-xs-4">
					<%= image_tag kid.avatar.thumb, class: "img-responsive circle-avatar img-circle kid" if kid.avatar.thumb.present? %>
					<br />
					<div class="caption">
						<%= link_to kid.name, kid_path(kid) %><br />
				 	</div><br />
		  		</div>
		  		<% end %>
		  	<br /><br />
		</div>
		<div class="col-xs-6">
			<h2 class="text-center">Upcoming Sits</h2> <br /><br />
		  		<% @family.sits.each do |sit| %>
		  		<div class="col-xs-4">
		  			<%= link_to sit.sit_start, new_sit_sitrequest_path(sit) %><br />
		  			From: <%= sit.sit_start %><br />
		  			To: <%= sit.sit_end %><br />
		  			<%= sit.sit_details %><br />
		  		</div>
		  		<% end %>
		  	<br /><br />
		</div>
	</div>
	<% end %>
</div>
<!-- End Section Kids --> 
	<% if @family.present? && @family.familysitters.present? %>
	<div class="col-xs-10 col-xs-offset-1">
		<h2 class="text-center">Sitters</h2>  <br /><br />
	  		<% @family.sitters.each do |sitter| %>
	  		<div class="col-xs-4 text-center">
	  			<div class="img-responsive">
	  				<%= image_tag sitter.avatar.thumb, class: "img-responsive img-circle circle-avatar adult" if sitter.avatar.thumb.present? %>
	  			</div><br />
				<div class="caption">
	  		 	<%= link_to sitter.first_name + " " + sitter.last_name, user_path(sitter) %><br />
	  			</div>
	  		</div>
	  		<% end %>
	  	<br /><br />
	</div>
<% end %>

	<% if (@user.sitteruser? || @user.parentsitteruser?) && @user.families.present?  %>
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
		<h2 class="text-center">Families I Sit For</h2>  <br /><br />
	  		<% @families.each do |family| %>
	  		<div class="col-xs-6">
	  		 	<div class="panel panel-default">
	    			<div class="panel-head-custom panel-heading">
	  				<%= image_tag family.avatar, class: "img-responsive special" if family.avatar.present? %>
	  				</div><br />
	  		 	<h4 class="text-center"><%= link_to "The " + family.name, family_path(family) %></h4>
	  			</div>
	  		</div>
	  		<% end %>
	  	<br /><br />
		</div>
	</div>

	<% end %>